language: python
dist: xenial
python:
- 3.7
script:
- python setup.py test
- echo "$TRAVIS_TAG"
- if [ -n "$TRAVIS_TAG" ]; then
  pip3 install twine;
  python3 setup.py sdist bdist_wheel;
  python3 -m twine upload dist/* -u lagmoellertim -p $TWINE --skip-existing;
  fi